# Generated by Django 3.2.9 on 2022-01-06 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20220106_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='room_id',
            new_name='room',
        ),
    ]
